name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          sudo apt-get install -y pandoc
          pip install sphinx sphinx_rtd_theme myst_parser nbsphinx pygments myst_parser sphinxcontrib-bibtex
          pip install ipython
      - name: Clean before build and transfer notebooks
        run: |
          rm -rf _build/
      - name: Sphinx build
        run: |
          sphinx-build ./docs _build
      - name: Create .nojekyll file
        run: |
          touch _build/.nojekyll
      - name: Copy PNG Images
        run: |
          cp *.png _build/ | true
          cp *.jpeg _build/ | true
          cp *.jpg _build/ | true
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
